"""initial schema (nine tables + binding indexes + FK cascade)

Revision ID: 0001
Revises:
Create Date: 2026-06-08 14:42:50.326010

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("num", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), server_default="", nullable=False),
        sa.Column("state", sa.Text(), server_default="backlog", nullable=False),
        sa.Column("labels_json", sa.Text(), server_default="[]", nullable=False),
        sa.Column("workflow_id", sa.Text(), nullable=True),
        sa.Column("agent", sa.Text(), nullable=True),
        sa.Column("pr_num", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.Column("sync_cursor", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("repo", "num", name="pk_issues"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("default_branch", sa.Text(), server_default="main", nullable=False),
        sa.Column("github_installation_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("engine_run_id", sa.Text(), nullable=True),
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("issue_num", sa.Integer(), nullable=True),
        sa.Column("workflow_id", sa.Text(), nullable=True),
        sa.Column("agent", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("branch", sa.Text(), nullable=True),
        sa.Column("feature_name", sa.Text(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default="0", nullable=False),
        sa.Column("turns", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column("pr_num", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("idempotency_key", name="uq_runs_idempotency_key"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index("ix_runs_issue_num", ["issue_num"], unique=False)
        batch_op.create_index("ix_runs_status_started_at", ["status", "started_at"], unique=False)

    op.create_table(
        "secrets",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_secrets")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    # events.id is INTEGER PRIMARY KEY AUTOINCREMENT (PRD §6.5): the monotonic
    # SSE replay cursor. ``sqlite_autoincrement=True`` emits the AUTOINCREMENT
    # keyword so ids are never reused even if events are retention-pruned later.
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("task_index", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("agent", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("run_id", "sequence", name="uq_events_run_id_sequence"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_run_id_id", ["run_id", "id"], unique=False)

    op.create_table(
        "pause_decisions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=True),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("answer_json", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Text(), nullable=True),
        sa.Column("timeout_at", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_pause_decisions_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pause_decisions")),
    )
    with op.batch_alter_table("pause_decisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_pause_decisions_status_timeout_at", ["status", "timeout_at"], unique=False
        )

    op.create_table(
        "run_stages",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("turns", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_stages_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id", "idx", name="pk_run_stages"),
    )
    op.create_table(
        "run_totals",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default="0", nullable=False),
        sa.Column("turns", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_totals_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_totals")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_totals")
    op.drop_table("run_stages")
    with op.batch_alter_table("pause_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_pause_decisions_status_timeout_at")

    op.drop_table("pause_decisions")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_run_id_id")

    op.drop_table("events")
    op.drop_table("settings")
    op.drop_table("secrets")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_status_started_at")
        batch_op.drop_index("ix_runs_issue_num")

    op.drop_table("runs")
    op.drop_table("projects")
    op.drop_table("issues")
    # ### end Alembic commands ###
